### ISSUE TITLE
Fatal error: Call to undefined function sqlsrv_connect()

### ISSUE THREAD

**Issue by haithem-rihane** [ShiZniTx/SambaWebReports#1]
Hi,

I 'm using PHP 5.5 and i added tp my php.ini under apache/conf
extension=php_pdo_sqlsrv_55_ts.dll
extension=php_sqlsrv_55_ts.dll

But i have this error :

Fatal error: Call to undefined function sqlsrv_connect() 

Note i'm using Windows7 64Bit Macine and Wampserver 2.5

**Comment by haithem-rihane** [comment]
Fix it , i need to install wamp server 32bit because php_pdo_sqlsrv_55_ts and php_sqlsrv_55_ts dosen't work on 64bit wamp.

**Comment by imshamim** [comment]
yes it will work when you use 64bit dll Download from : 
http://robsphp.blogspot.com/2012/06/unofficial-microsoft-sql-server-driver.html

You can read it from here:
https://stackoverflow.com/questions/18459658/call-to-undefined-function-sqlsrv-connect-in-c-wamp-www-webs-client-php-on-li
